receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      memory: {}
      filesystem: {}
      load: {}
      network: {}

processors:
  batch:
  memory_limiter:
    limit_mib: 512
    check_interval: 1s

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: "mcp-gateway"

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  debug: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, batch]
      exporters: [prometheus, debug]