// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: validate_import.proto

package validate

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message that simply references the validate import so the module is used.
type Unused struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unused) Reset() {
	*x = Unused{}
	mi := &file_validate_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unused) ProtoMessage() {}

func (x *Unused) ProtoReflect() protoreflect.Message {
	mi := &file_validate_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unused.ProtoReflect.Descriptor instead.
func (*Unused) Descriptor() ([]byte, []int) {
	return file_validate_import_proto_rawDescGZIP(), []int{0}
}

var File_validate_import_proto protoreflect.FileDescriptor

const file_validate_import_proto_rawDesc = "" +
	"\n" +
	"\x15validate_import.proto\x12\x0fvalidate_import\x1a\x17validate/validate.proto\"\b\n" +
	"\x06UnusedB\x12Z\x10./proto/validateb\x06proto3"

var (
	file_validate_import_proto_rawDescOnce sync.Once
	file_validate_import_proto_rawDescData []byte
)

func file_validate_import_proto_rawDescGZIP() []byte {
	file_validate_import_proto_rawDescOnce.Do(func() {
		file_validate_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validate_import_proto_rawDesc), len(file_validate_import_proto_rawDesc)))
	})
	return file_validate_import_proto_rawDescData
}

var file_validate_import_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_validate_import_proto_goTypes = []any{
	(*Unused)(nil), // 0: validate_import.Unused
}
var file_validate_import_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_validate_import_proto_init() }
func file_validate_import_proto_init() {
	if File_validate_import_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validate_import_proto_rawDesc), len(file_validate_import_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_validate_import_proto_goTypes,
		DependencyIndexes: file_validate_import_proto_depIdxs,
		MessageInfos:      file_validate_import_proto_msgTypes,
	}.Build()
	File_validate_import_proto = out.File
	file_validate_import_proto_goTypes = nil
	file_validate_import_proto_depIdxs = nil
}
