// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: weather/weather.proto

package weather

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Units         string                 `protobuf:"bytes,2,opt,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherRequest) Reset() {
	*x = GetWeatherRequest{}
	mi := &file_weather_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherRequest) ProtoMessage() {}

func (x *GetWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherRequest) Descriptor() ([]byte, []int) {
	return file_weather_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetWeatherRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetWeatherRequest) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

type GetWeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float64                `protobuf:"fixed64,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Conditions    string                 `protobuf:"bytes,2,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Humidity      uint32                 `protobuf:"varint,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Units         string                 `protobuf:"bytes,4,opt,name=units,proto3" json:"units,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherResponse) Reset() {
	*x = GetWeatherResponse{}
	mi := &file_weather_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherResponse) ProtoMessage() {}

func (x *GetWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherResponse) Descriptor() ([]byte, []int) {
	return file_weather_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeatherResponse) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GetWeatherResponse) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

func (x *GetWeatherResponse) GetHumidity() uint32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *GetWeatherResponse) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

func (x *GetWeatherResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type GetWeatherForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Units         string                 `protobuf:"bytes,3,opt,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherForecastRequest) Reset() {
	*x = GetWeatherForecastRequest{}
	mi := &file_weather_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherForecastRequest) ProtoMessage() {}

func (x *GetWeatherForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherForecastRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherForecastRequest) Descriptor() ([]byte, []int) {
	return file_weather_weather_proto_rawDescGZIP(), []int{2}
}

func (x *GetWeatherForecastRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetWeatherForecastRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetWeatherForecastRequest) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

type GetWeatherForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float64                `protobuf:"fixed64,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Conditions    string                 `protobuf:"bytes,2,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Humidity      uint32                 `protobuf:"varint,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Units         string                 `protobuf:"bytes,6,opt,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherForecastResponse) Reset() {
	*x = GetWeatherForecastResponse{}
	mi := &file_weather_weather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherForecastResponse) ProtoMessage() {}

func (x *GetWeatherForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_weather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherForecastResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherForecastResponse) Descriptor() ([]byte, []int) {
	return file_weather_weather_proto_rawDescGZIP(), []int{3}
}

func (x *GetWeatherForecastResponse) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GetWeatherForecastResponse) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

func (x *GetWeatherForecastResponse) GetHumidity() uint32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *GetWeatherForecastResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetWeatherForecastResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetWeatherForecastResponse) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

var File_weather_weather_proto protoreflect.FileDescriptor

const file_weather_weather_proto_rawDesc = "" +
	"\n" +
	"\x15weather/weather.proto\x12\x10examples.weather\x1a\x1bbuf/validate/validate.proto\"\xab\x04\n" +
	"\x11GetWeatherRequest\x12#\n" +
	"\blocation\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\blocation\x12-\n" +
	"\x05units\x18\x02 \x01(\tB\x17\xbaH\x14r\x12R\x06metricR\bimperialR\x05units:\xc1\x03\xbaH\xbd\x03\x1a\xba\x03\n" +
	"\x19request_complex_semantics\x12Eimperial requires US location; location must be a readable place name\x1a\xd5\x02(this.units == 'imperial' ? (this.location.endsWith('US') || this.location.endsWith('USA') || this.location.endsWith('United States')) : !(this.location.endsWith('US') || this.location.endsWith('USA') || this.location.endsWith('United States'))) && size(this.location) >= 2 && !this.location.startsWith('-') && !this.location.startsWith(' ')\"\xa4\x01\n" +
	"\x12GetWeatherResponse\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x01R\vtemperature\x12\x1e\n" +
	"\n" +
	"conditions\x18\x02 \x01(\tR\n" +
	"conditions\x12\x1a\n" +
	"\bhumidity\x18\x03 \x01(\rR\bhumidity\x12\x14\n" +
	"\x05units\x18\x04 \x01(\tR\x05units\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\"\xd1\x04\n" +
	"\x19GetWeatherForecastRequest\x12#\n" +
	"\blocation\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\blocation\x12\x1b\n" +
	"\x04date\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04date\x12-\n" +
	"\x05units\x18\x03 \x01(\tB\x17\xbaH\x14r\x12R\x06metricR\bimperialR\x05units:\xc2\x03\xbaH\xbe\x03\x1a\xbb\x03\n" +
	"\x1aforecast_complex_semantics\x12Eimperial requires US location; location must be a readable place name\x1a\xd5\x02(this.units == 'imperial' ? (this.location.endsWith('US') || this.location.endsWith('USA') || this.location.endsWith('United States')) : !(this.location.endsWith('US') || this.location.endsWith('USA') || this.location.endsWith('United States'))) && size(this.location) >= 2 && !this.location.startsWith('-') && !this.location.startsWith(' ')\"\xc0\x01\n" +
	"\x1aGetWeatherForecastResponse\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x01R\vtemperature\x12\x1e\n" +
	"\n" +
	"conditions\x18\x02 \x01(\tR\n" +
	"conditions\x12\x1a\n" +
	"\bhumidity\x18\x03 \x01(\rR\bhumidity\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x14\n" +
	"\x05units\x18\x06 \x01(\tR\x05units2\xda\x01\n" +
	"\x0eWeatherService\x12W\n" +
	"\n" +
	"GetWeather\x12#.examples.weather.GetWeatherRequest\x1a$.examples.weather.GetWeatherResponse\x12o\n" +
	"\x12GetWeatherForecast\x12+.examples.weather.GetWeatherForecastRequest\x1a,.examples.weather.GetWeatherForecastResponseB\x1aZ\x18mcp-server/proto/weatherb\x06proto3"

var (
	file_weather_weather_proto_rawDescOnce sync.Once
	file_weather_weather_proto_rawDescData []byte
)

func file_weather_weather_proto_rawDescGZIP() []byte {
	file_weather_weather_proto_rawDescOnce.Do(func() {
		file_weather_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weather_weather_proto_rawDesc), len(file_weather_weather_proto_rawDesc)))
	})
	return file_weather_weather_proto_rawDescData
}

var file_weather_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_weather_weather_proto_goTypes = []any{
	(*GetWeatherRequest)(nil),          // 0: examples.weather.GetWeatherRequest
	(*GetWeatherResponse)(nil),         // 1: examples.weather.GetWeatherResponse
	(*GetWeatherForecastRequest)(nil),  // 2: examples.weather.GetWeatherForecastRequest
	(*GetWeatherForecastResponse)(nil), // 3: examples.weather.GetWeatherForecastResponse
}
var file_weather_weather_proto_depIdxs = []int32{
	0, // 0: examples.weather.WeatherService.GetWeather:input_type -> examples.weather.GetWeatherRequest
	2, // 1: examples.weather.WeatherService.GetWeatherForecast:input_type -> examples.weather.GetWeatherForecastRequest
	1, // 2: examples.weather.WeatherService.GetWeather:output_type -> examples.weather.GetWeatherResponse
	3, // 3: examples.weather.WeatherService.GetWeatherForecast:output_type -> examples.weather.GetWeatherForecastResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weather_weather_proto_init() }
func file_weather_weather_proto_init() {
	if File_weather_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weather_weather_proto_rawDesc), len(file_weather_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weather_weather_proto_goTypes,
		DependencyIndexes: file_weather_weather_proto_depIdxs,
		MessageInfos:      file_weather_weather_proto_msgTypes,
	}.Build()
	File_weather_weather_proto = out.File
	file_weather_weather_proto_goTypes = nil
	file_weather_weather_proto_depIdxs = nil
}
